version: '3.7'

services:
  db:
    container_name: mysql-local-example
    image: mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    restart: always

  phpmyadmin:
    container_name: phpmyadmin-local-example
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    restart: always

#  ALTER USER 'admin' IDENTIFIED WITH mysql_native_password BY 'admin'
